version: "3.3"

networks:
  thecracknetwork:

services:
  www:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db_server
      - db_admin
    networks:
      - thecracknetwork

  db_server:
    image: mysql
    container_name: 'TheCrack-db'
    environment:
      MYSQL_USER: aperellop
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: pwdroot
      MYSQL_DATABASE: TheCrackDB
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - thecracknetwork

  db_admin:
    image: phpmyadmin/phpmyadmin
    container_name: 'TheCrack-db_admin'
    links:
     - db_server:db
    ports:
     - 8080:80
    environment:
      MYSQL_USER: aperellop
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: pwd
    networks:
      - thecracknetwork
volumes:
  persistent: